name: Build
on:
    push:
        paths:
            - 'buildozer.spec'
            - 'src/**'
        branches-ignore:
            - master

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get Date
              id: get-date
              run: |
                echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Build with Buildozer
              uses: ArtemSBulgakov/buildozer-action@v1
              id: buildozer
              with:
                command: sudo apt update && sudo apt install -y openjdk-17-jdk; pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer; buildozer android debug
                buildozer_version: master
