name: Build
on:
    push:
        paths:
            - 'buildozer.spec'
            - 'src/**'
            - '.github/**'
        #branches:
        #    - master

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Prepare environment
              run: sudo apt-get install -y libevent-dev git

            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: master
                fetch-depth: 0
                ref: ${{ github.head_ref }}

            - name: Get Date
              id: get-date
              run: |
                echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Git Version
              id: version
              uses: codacy/git-version@2.8.0

            - name: Update VERSION file
              run: |
                echo ${{ steps.version.outputs.version }} >> ./master/src/VERSION
                git add ./master/src/VERSION
                git commit -m 'VERSION is updated by CI'
                git push

#            - name: Build with Buildozer
#              uses: ArtemSBulgakov/buildozer-action@v1
#              id: buildozer
#              with:
#                repository_root: ./master
#                command: sudo apt update && sudo apt install -y openjdk-17-jdk; pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer; buildozer android debug
#                buildozer_version: master

#            - name: Checkout
#              uses: actions/checkout@v4
#              with:
#                path: data
#                ref: data
              
#            - name: Push binary to data branch
#              run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
