name: Build
on:
    push:
        paths:
            - 'buildozer.spec'
            - 'playlistcreator.spec'
            - 'src/**'
            - '.github/**'
        #branches:
        #    - master

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get Date
              id: get-date
              run: |
                echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Build with Buildozer
              uses: ArtemSBulgakov/buildozer-action@v1
              id: buildozer
              with:
                command: sudo apt update && sudo apt install -y openjdk-17-jdk; pip3 install --user --upgrade Cython==0.29.33 virtualenv; pip3 install --user --upgrade buildozer; buildozer -v android debug
                buildozer_version: master

            - name: Switch to data branch
              run: git switch data
              
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'
                architecture: x64
              
            - name: Push binary to data branch
              if: github.event_name == 'push'
              run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin

    pyinstaller-build:
        name: Build for Windows
        runs-on: windows-latest

        steps:
            - name: Build with PyInstaller
              uses: sayyid5416/pyinstaller@v1
              id: pyinstaller
              with:
                python_ver: '3.11'
                spec: 'playlistcreator.spec'
                requirements: 'requirements-dev.txt'
                upload_exe_with_name: 'playlistcreator'

            - name: Switch to data branch
              run: git switch data
                
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'
                architecture: x64
                
            - name: Push executable to data branch
              if: github.event_name == 'push'
              run: python master/.ci/move_binary.py "${{ steps.pyinstaller.outputs.filename }}" master data dist
