name: Build
on:
    push:
        paths:
            - 'buildozer.spec'
            - 'src/**'
        branches:
            - master

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                persist-credentials: false

            - name: Get Date
              id: get-date
              run: |
                echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Build with Buildozer
              uses: ArtemSBulgakov/buildozer-action@v1
              id: buildozer
              with:
                command: sudo apt update && sudo apt install -y openjdk-17-jdk; pip3 install --user --upgrade Cython==0.29.33 virtualenv; pip3 install --user --upgrade buildozer; buildozer android debug
                buildozer_version: master

            - name: Switch to data branch
              run: |
                git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
                git fetch origin data
                git checkout data
              
            - name: Push binary to data branch
              if: github.event_name == 'push'
              run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
