name: Build
on:
    pull_request:
        types:
            - opened
    push:
        paths:
            - '.github/**'
            - 'buildozer.spec'

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Install JDK 17
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: '17'
                cache: 'gradle'

            - name: Install JRE 17
              run: sudo apt install openjdk-17-jre

            - name: Checkout
              uses: actions/checkout@v2

            - name: Get Date
              id: get-date
              run: |
                echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
              shell: bash
      
            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}
      
            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Build with Buildozer
              uses: ArtemSBulgakov/buildozer-action@v1
              id: buildozer
              with:
                command: pip3 install --user --upgrade Cython==0.29.33 virtualenv; pip3 install --user --upgrade buildozer; buildozer -v android debug
                buildozer_version: master
