name: Build and publish
on:
    push:
        paths:
            - 'buildozer.spec'
            - 'src/**'
        branches:
            - master

jobs:
    build-android:
        name: Build for Android
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: master
                fetch-depth: 0
            
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v2.0.0
              with:
                versionSpec: '5.x'

            - name: Get Date
              id: get-date
              run: |
                echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache Buildozer global directory
              uses: actions/cache@v2
              with:
                path: .buildozer_global
                key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - uses: actions/cache@v2
              with:
                path: .buildozer
                key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

            - name: Determine Version
              uses: gittools/actions/gitversion/execute@v2.0.0
              id: version
              with:
                targetPath: ${{ github.workspace }}/master

            - name: Update VERSION file
              run: |
                cd ${{ github.workspace }}/master
                echo ${{ steps.version.outputs.majorMinorPatch }} > src/VERSION
                git config user.email "github-action@users.noreply.github.com"
                git config user.name "Github Action"
                git config user.password "${{ github.token }}"
                git add src/VERSION
                git commit -m 'VERSION is updated by CI' && git push || echo "No new version detected" 
                git tag ${{ steps.version.outputs.majorMinorPatch }} ${{ github.sha }}
                cd ${{ github.workspace }}

            - name: Build with Buildozer
              uses: ArtemSBulgakov/buildozer-action@v1
              id: buildozer
              with:
                repository_root: ./master
                command: sudo apt update && sudo apt install -y openjdk-17-jdk; pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer; buildozer android debug
                buildozer_version: master

            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: data
                ref: data
              
            - name: Push binary to data branch
              run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
